FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
COPY bin/Release/net6.0/publish/ .
COPY appsettings.json /app/
COPY aspnetapp.pfx /app/

ENV ASPNETCORE_ENVIRONMENT="Development"
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true

ENV DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 80
ENTRYPOINT ["dotnet", "MaxMelcher.GHEAADProxy.dll"]